spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/weather
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: yes
    format_sql: true
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  api-docs:
    path: /weather-openapi
API:
  url: https://api.openweathermap.org/data/2.5/forecast?units=metric&appid=3ab9890e603db3803ca52c1a436bb816&q=
  cities: Novi Sad, Malmo, Rethymno
